# Generated by Django 6.1.1 on 2026-09-09 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('devise', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Utilisez un code devise de trois lettres majuscules.')])),
                ('statut_paiement', models.CharField(choices=[('non_paye', 'Non payé'), ('partiel', 'Partiel'), ('paye', 'Payé')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_clients', to='orders.dossieradministratif')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('devise', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Utilisez un code devise de trois lettres majuscules.')])),
                ('date_facture', models.DateField()),
                ('statut_traitement', models.CharField(choices=[('a_traiter', 'À traiter'), ('traitee', 'Traitée')], default='a_traiter', max_length=20)),
                ('statut_paiement', models.CharField(choices=[('a_payer', 'À payer'), ('paye', 'Payé')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='orders.commandefournisseur')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='orders.dossieradministratif')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='suppliers.fournisseur')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
