# Generated by Django 6.1.1 on 2026-09-09 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('orders', '0001_initial'),
        ('receptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=100)),
                ('fichier', models.FileField(max_length=255, upload_to='documents/%Y/%m/')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='orders.commandefournisseur')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='orders.dossieradministratif')),
                ('facture_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='invoices.factureclient')),
                ('facture_fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='invoices.facturefournisseur')),
                ('reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='receptions.reception')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('commande__isnull', True), ('dossier__isnull', False), ('facture_client__isnull', True), ('facture_fournisseur__isnull', True), ('reception__isnull', True)), models.Q(('commande__isnull', False), ('dossier__isnull', True), ('facture_client__isnull', True), ('facture_fournisseur__isnull', True), ('reception__isnull', True)), models.Q(('commande__isnull', True), ('dossier__isnull', True), ('facture_client__isnull', True), ('facture_fournisseur__isnull', True), ('reception__isnull', False)), models.Q(('commande__isnull', True), ('dossier__isnull', True), ('facture_client__isnull', True), ('facture_fournisseur__isnull', False), ('reception__isnull', True)), models.Q(('commande__isnull', True), ('dossier__isnull', True), ('facture_client__isnull', False), ('facture_fournisseur__isnull', True), ('reception__isnull', True)), _connector='OR'), name='document_exactly_one_owner')],
            },
        ),
    ]
